<?php
echo "<!doctype html>\n";
echo "<html>\n";
echo "<head>\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <link href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n";
echo "	<title>b0942100</title>\n";
echo "\n";
echo "	<style>\n";
echo "    body{\n";
echo "   background-image: url(media/987.jpg);\n";
echo "            background-repeat: no-repeat;\n";
echo "            background-attachment: fixed;\n";
echo "            background-position: center;\n";
echo "            background-size: cover;}\n";
echo "\n";
echo "    </style>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<header> \n";
echo "  <p class=\"h3\"><font color=\"red\">期末專題</font></p>\n";
echo "\n";
echo "<nav class=\"navbar navbar-default\">\n";
echo "  <!-- 選單 -->\n";
echo "  <div id=\"mynav\" class=\"navbar-collapse collapse\">\n";
echo "    <ul class=\"navbar-nav nav\">\n";
echo "      <li><a href=\"https://www.instagram.com/tv/CJI9ErxgYc9/\"><!-- 選單項目 1 -->宜蘭電子系學會</a></li>\n";
echo "      <li><a href=\"https://euni.niu.edu.tw/\"><!-- 選單項目 2 -->宜蘭數位m園區</a></li>\n";
echo "      <li><a href=\"https://www.niu.edu.tw/bin/home.php\"><!-- 選單項目 3 -->宜蘭大學</a></li>\n";
echo "    </ul>\n";
echo "  </div>\n";
echo "</nav>\n";
echo "</header>\n";
echo "\n";
echo "\n";
echo "<form name=\"login\" action=\"http://httpbin.org/get\" method=\"get\">\n";
echo "                                                                    \n";
echo "  <font color=\"red\">帳號：</font><input name=\"account\" type=\"text\" size=\"8\"><br>\n";
echo "  <font color=\"red\">密碼：</font><input name=\"pass\" type=\"password\" size=\"8\"><br>\n";
echo "       <input type=\"submit\" value=\"登入\">\n";
echo "  </form>   \n";
echo "  <img src=\"media/spider_man_PNG97.png\" >\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";
?>